/**
 * Represents a result of a direct flow execution.
 */
export class FlowResult {
    /**
     * Represents the access token generated by the flow excecution.
     */
    public accessToken:string;
    /**
     * Represents the refresh token generated by the flow excecution.
     */
    public refreshToken:string;
    /**
     *Represents the time in which the access token will expire.
     */
    public expireIn:number;
    /**
     * Represents an state to validate the authenticity of the response result.
     */
    public state:string;
}