import { BaseFlow } from './BaseFlow'
import { IFlowHandler } from '../IFlowHandler'

/**
 * Represents a code exchange flow.
 */
export class CodeExchangeFlow extends BaseFlow {
    constructor() {
        super('code_exchange');
    }

    /**
     * Get or set the code generated by the authorization code flow.
     */
    public code:string;

    /**
     * Get or set the redirection url used in the authorization code flow.
     */
    public redirectUri:string;

   /**
     * Get or set the client secret for the flow authentication.
     */
    public clientSecret:string;   

    /**
     * Execute the flow and handle it with the given handler.
     * @param handler Represents the handler for the flow.
     */
    public execute(handler:IFlowHandler):void {  

       
    }
}